main: com.rooxchicken.infinity.Infinity
name: InfinityPlugin
version: 0.1
api-version: '1.21'

commands:
   hdn_ability1_srt:
      description: First ability START
      usage: /hdn_ability1_srt

   hdn_ability2_srt:
      description: Second ability START
      usage: /hdn_ability2_srt

   hdn_ability1_rpt:
         description: First ability REPEAT
         usage: /hdn_ability1_rpt

   hdn_ability2_rpt:
         description: Second ability REPEAT
         usage: /hdn_ability2_rpt

   hdn_ability1_end:
         description: First ability END
         usage: /hdn_ability1_end
         
   hdn_ability2_end:
      description: Second ability END
      usage: /hdn_ability2_end

   hdn_verifymod:
      description: Client verification of mod
      usage: /hdn_verifymod

   skilltree:
      description: Opens the skill tree
      usage: /skilltree

   hdn_action:
      description: Attempts to activate a node
      usage: /hdn_action

   setpoints:
      description: Sets a player's points
      usage: /setpoints <number>

   resetcooldown:
      description: Resets all cooldowns
      usage: /resetcooldown

   resettree:
      description: Resets all tree data
      usage: /resettree

   addallpoints:
      description: Gives every player points
      usage: /addallpoints <number>
      
depend: [ ProtocolLib ]